### ISSUE TITLE
去升级版的脚本目录，能否添加出来呢。

### ISSUE THREAD

**Issue by MangoDong** [Zy143L/jdc#1]

**Comment by Zy143L** [comment]
可以的..
docerk创建的时候 把script目录映射出来就行了

**Comment by MangoDong** [comment]
好的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月22日(周二) 下午4:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Zy143L/jdc] 去升级版的脚本目录，能否添加出来呢。 (#1)




 
可以的..
 docerk创建的时候 把script目录映射出来就行了
