### ISSUE TITLE
显示添加成功后，接着显示连接服务器失败，2.2没有cookie

### ISSUE THREAD

**Issue by TEAMO233** [Zy143L/jdc#13]
老哥们，有遇到过吗

**Comment by ID404** [comment]
> 老哥们，有遇到过吗

我也遇到同样的问题
2021/07/11 22:36:24 [SUCCESS] Cron is running!
2021-07-11 22:36:24.263 [DEBU] SetServerRoot path: /ql/config/JDC/public
2021-07-11 22:36:24.266 21518: http server started listening on [:5701]
2021/07/11 22:36:42 error！can't read cookieList!
2021/07/11 22:36:42 error！can't read cookieList!

**Comment by Zy143L** [comment]
> > 老哥们，有遇到过吗
> 
> 我也遇到同样的问题
> 2021/07/11 22:36:24 [SUCCESS] Cron is running!
> 2021-07-11 22:36:24.263 [DEBU] SetServerRoot path: /ql/config/JDC/public
> 2021-07-11 22:36:24.266 21518: http server started listening on [:5701]
> 2021/07/11 22:36:42 error！can't read cookieList!
> 2021/07/11 22:36:42 error！can't read cookieList!

你这个是2,8吧

**Comment by ID404** [comment]
> > > 老哥们，有遇到过吗
> > 
> > 
> > 我也遇到同样的问题
> > 2021/07/11 22:36:24 [SUCCESS] Cron is running!
> > 2021-07-11 22:36:24.263 [DEBU] SetServerRoot path: /ql/config/JDC/public
> > 2021-07-11 22:36:24.266 21518: http server started listening on [:5701]
> > 2021/07/11 22:36:42 error！can't read cookieList!
> > 2021/07/11 22:36:42 error！can't read cookieList!
> 
> 你这个是2,8吧

确实是2.8的

**Comment by Zy143L** [comment]
> > > > 老哥们，有遇到过吗
> > > 
> > > 
> > > 我也遇到同样的问题
> > > 2021/07/11 22:36:24 [SUCCESS] Cron is running!
> > > 2021-07-11 22:36:24.263 [DEBU] SetServerRoot path: /ql/config/JDC/public
> > > 2021-07-11 22:36:24.266 21518: http server started listening on [:5701]
> > > 2021/07/11 22:36:42 error！can't read cookieList!
> > > 2021/07/11 22:36:42 error！can't read cookieList!
> > 
> > 
> > 你这个是2,8吧
> 
> 确实是2.8的

这个版本的JDC适用于2.2版本
