### ISSUE TITLE
关于连接服务器失败

### ISSUE THREAD

**Issue by Qinhank** [Zy143L/jdc#15]
今天弄了一下，发现2.8.0版本是把cookie.sh和cookie.db改成env.sh和env.db了，但是JDC还没更新，所以导致cookie无法写入，报：
**open /ql/config/cookie.sh: no such file or directory**。
解决：
使用别人修改的版本
地址：https://github.com/Liquid-w/JDC

**Comment by Zy143L** [comment]
我这个版本就是针对2.2的..2.8建议换其他师傅的
