### ISSUE TITLE
arm64 debian10 国外机 2.2-066 能扫码但不显示昵称，session管理空白

### ISSUE THREAD

**Issue by zhuanke8** [Zy143L/jdc#22]
arm64 debian10 国外机 2.2-066 能扫码但不显示昵称，session管理空白
![image.png](https://ae03.alicdn.com/kf/U29935cf1577643e1b461e199910a9a25W.png)
![image.png](https://ae05.alicdn.com/kf/Uad076204f35d4e468a6cffdbb52a5d540.png)
![image.png](https://ae03.alicdn.com/kf/U8b643f9e98f348e29ccc1af3358402203.png)

**Comment by Zy143L** [comment]
国外机子就不知道了
而且很不推荐国外件机子搭建脚本 很容易导致账号被风控
