### ISSUE TITLE
2.2jdc

### ISSUE THREAD

**Issue by timessage** [Zy143L/jdc#26]
服务器已离线，节点那也是空的

**Comment by niuniudada** [comment]
我刚刚拉取的代码，服务器运行后显示：
![image](https://user-images.githubusercontent.com/12442026/128286784-f79e9f28-bc51-4815-bffb-bb0654da39d8.png)

配置文件，运行文件都没有更改，都是master拉取的。

**Comment by Zy143L** [comment]
这个2.2文件是给已有环境变量的JDC用户提供的
新用户建议使用青龙2.8+Ninja的配合
