### ISSUE TITLE
扫码失效了

### ISSUE THREAD

**Issue by cmazfuture** [Zy143L/jdc#27]
突然扫码失效了，扫完页面没反应

**Comment by Zy143L** [comment]
能详细些?

**Comment by cmazfuture** [comment]
就是扫完码，点确认登录，网页端JDC没跳转。就停留在二维码页面，。已经最新版JDC

**Comment by Zy143L** [comment]
config中对UA进行设置了吗?

**Comment by cmazfuture** [comment]
开始没反应，后来尝试了对UA进行设置也不行。设置的UA = "Mozilla/5.0 (iPhone; CPU iPhone OS 13_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 SP-engine/2.14.0 main/1.0 baiduboxapp/11.18.0.16 (Baidu; P2 13.3.1) NABar/0.0"

**Comment by Zy143L** [comment]
设置完成UA后 杀掉JDC再开

**Comment by cmazfuture** [comment]
设置完成UA，我直接重启了服务器。。

**Comment by cmazfuture** [comment]
这个应该比杀掉JDC更有效吧

**Comment by cmazfuture** [comment]
您试试外网扫二维码，就是和JDC不在一个IP下扫码。

**Comment by Zy143L** [comment]
晚些时间我看看吧...个人推荐你上Ninja

**Comment by cmazfuture** [comment]
好的，谢谢，我试试ninja

**Comment by cmazfuture** [comment]
刚试着搭建了ninja。。才发现ninjia只支持青龙2.8  0.0   我的2.2
