### ISSUE TITLE
部分账号无法扫码，扫码后导致面板ck管理白板

### ISSUE THREAD

**Issue by Coolrui1816** [Zy143L/jdc#29]
不知道是JDC的问题还是ql问题。。麻烦作者看一下

<img width="659" alt="QQ20210808-153721@2x" src="https://user-images.githubusercontent.com/56864168/128624688-199fb433-5f99-4f56-b43b-9b12bb8f59c4.png">

部分号扫码后显示，有些账号又正常
<img width="413" alt="QQ20210808-153930@2x" src="https://user-images.githubusercontent.com/56864168/128624727-a63e75dd-f50a-4a94-b17a-62ae144b293c.png">

使用最新您发的JDC和UA

**Comment by VwEl** [comment]
其实这是CK的问题：你添加会引起这种问题的CK，青龙就会卡住，在刷新就空白了，不知道什么原因

**Comment by Zy143L** [comment]
这个问题我也没遇到过..如果有问题的话 推荐上青龙2.8配合ninja使用

**Comment by spiritLHL** [comment]
ninja最近没更新了，跳转页面部分也有bug

**Comment by VwEl** [comment]
错误原因是Unexpected end of JSON input

**Comment by Coolrui1816** [comment]
> 其实这是CK的问题：你添加会引起这种问题的CK，青龙就会卡住，在刷新就空白了，不知道什么原因

是的，目前只能删除问题ck。。

**Comment by Coolrui1816** [comment]
> 实际上青这是CK的问题：你添加会引起流行的问题的CK，龙会住，在刷新就空闲了，不知道什么原因

是的，目前只能删除问题ck来恢复列表。。

**Comment by renzcu** [comment]
折腾来折腾去原来是ck的问题。。。
