### ISSUE TITLE
新版启动不了

### ISSUE THREAD

**Issue by dawei233** [Zy143L/jdc#3]
![image](https://user-images.githubusercontent.com/31338729/123580643-d59d6000-d80c-11eb-9841-bd8fc50f54dc.png)
新版提示找不到文件或目录老版本没这报错可以正常执行

**Comment by dawei233** [comment]
limoe/qinglong
用的是这个容器 重建以后还是一样执行不了

**Comment by rikkishi** [comment]
我也是这样

**Comment by dawei233** [comment]
已经放弃了我放在容器外面跑了

**Comment by mjyhj** [comment]
我也一样，用旧的可以，新版就这样

**Comment by Patickhuang** [comment]
对 在openwrt也用不了 等待大佬修复

**Comment by nssiwi** [comment]
确实使用不了，`sh ./JDC` 会输一串乱码

**Comment by Zy143L** [comment]
apk add libc6-compat

**Comment by Zy143L** [comment]
> 对 在openwrt也用不了 等待大佬修复

openwrt缺少tzdata 后续会想办法
