### ISSUE TITLE
更换了ua，二维码能变换了。但是扫码之后不跳转

### ISSUE THREAD

**Issue by Yousefcheng** [Zy143L/jdc#32]
更换了ua之后，二维码能变换了。但是扫码之后不跳转，ck也没添加

**Comment by imwcc** [comment]
同问,我也遇到了

**Comment by imwcc** [comment]
Hi @Zy143L 

帮忙看看呗

**Comment by imwcc** [comment]
另外可以介绍一下 在那个UI 抓UA吗?
感谢

**Comment by Yousefcheng** [comment]
自己的电脑的ua和抓包的ua都试了，都不行，请问大佬有解决办法么？

**Comment by imwcc** [comment]
下面这个接口是有问题的,不应该调用了

> 0|panel    | FetchError: invalid json response body at https://me-api.jd.com/user_new/info/GetJDUserInfoUnion reason: Unexpected end of JSON input
> 0|panel    |     at /ql/node_modules/.pnpm/node-fetch@2.6.1/node_modules/node-fetch/lib/index.js:272:32
> 0|panel    |     at processTicksAndRejections (internal/process/task_queues.js:95:5) {
> 0|panel    |   type: 'invalid-json'
> 0|panel    | }
>

**Comment by Yousefcheng** [comment]
我找到了解决办法，在ua后面加一个 UCBrowser/13.4.2.1122  就可以跨网了

**Comment by imwcc** [comment]
> 我找到了解决办法，在ua后面加一个 UCBrowser/13.4.2.1122 就可以跨网了

感谢

**Comment by spiritLHL** [comment]
不知道为什么扫码完老是提示服务器连接失败。。。

**Comment by Zy143L** [comment]
Mozilla/5.0 (iPhone; U; CPU iPhone OS 4_3_2 like Mac OS X; en-us) AppleWebKit/533.17.9 (KHTML, like Gecko) Version/5.0.2 Mobile/8H7 Safari/6533.18.5 UCBrowser/13.4.2.1122
