### ISSUE TITLE
AMD64的，在docker里跑不了，在缩主机可以

### ISSUE THREAD

**Issue by mjyhj** [Zy143L/jdc#5]
有没有人一样的，知道是什么问题不？

路径对，权限对，后台无进程
旧版： 缩主机 和docker里都能运行
新版：缩主机里可以运行，docker里不能运行

![1](https://user-images.githubusercontent.com/22577418/123592502-dbe90780-d81f-11eb-9c61-330885ec54da.png)

**Comment by dhbowen1** [comment]
root@qinglong:/ql $ cd /ql/config&&nohup ./JDC
nohup: ignoring input and appending output to 'nohup.out'
nohup: failed to run command './JDC': No such file or directory

一样的情况，群晖docker不能运行，路径什么的都正常。切换为老版就可以运行。

**Comment by dhbowen1** [comment]
大佬能检查下后端什么情况吗？docker无法运行。期盼大佬尽快解决

**Comment by ericchan985** [comment]
盼望早点  修好

**Comment by imwcc** [comment]
同问，我也遇到这个问题了
我用的v3,v4 还有青龙都报找不到文件
有可能是 链接库找不到了

**Comment by imwcc** [comment]
apk add libc6-compat

**Comment by dhbowen1** [comment]
> 同问，我也遇到这个问题了
> 我用的v3,v4 还有青龙都报找不到文件
> 有可能是 链接库找不到了

解决了吗？

**Comment by Myrkursins888** [comment]
> apk 添加 libc6-compat

运行之后可以了

**Comment by Zy143L** [comment]
@imwcc 多谢 

```
apk add libc6-compat
```
