### ISSUE TITLE
大佬，端口监听格式可以优化一下吗

### ISSUE THREAD

**Issue by seatom** [Zy143L/jdc#7]
当前版本在centos7下5701端口默认被tcp6监听了，导致ipv4下打不开面板

可以参考这个格式http://httpd.apache.org/docs/2.0/bind.html#ipv6

![image](https://user-images.githubusercontent.com/17746264/123667552-d665de80-d86c-11eb-968f-dcb1459c6853.png)

**Comment by hdstar2009** [comment]
改jdc和qinglong的配置，可以做到任何端口
